name: The Foundry - Coworking Belfast
markdown: redcarpet
highlighter: pygments # or rouge or null
baseurl: /the-foundry
url: thefoundrybelfast.github.io
exclude: ['node_modules', 'gulpfile.js', 'package.json', 'src', 'Gemfile', 'Gemfile.lock']
